#!/bin/bash

echo
echo "****************************************************"
echo "This script will delete all the data on the project!"
echo "****************************************************"
echo

read -p "Are you sure you want to continue? (yes/no) "
if [ "$REPLY" != "yes" ]; then
  exit
fi
echo

echo "Checking Secrets ..."
if [ -f secrets.json ]; then
  echo "[ERROR] This looks like a production environment! Aborting ..."; echo; exit 1
fi
echo "Done"

echo "Deleting virtual environment (venv) ..."
rm -rf ~/venv
echo "Done"

echo "Deleting database folder (data) ..."
rm -rf data/
echo "Done"

echo "Environment Clean!"
echo

# 2018.06.01-DEA
