# Generated by Django 2.0 on 2018-10-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_scheduled_hours', models.IntegerField(blank=True, null=True)),
                ('type_of_employee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('hours', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='available_shifts',
            field=models.ManyToManyField(blank=True, related_name='available_shifts', to='website.Shift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='scheduled_shifts',
            field=models.ManyToManyField(blank=True, related_name='scheduled_shifts', to='website.Shift'),
        ),
    ]
