# Generated by Django 2.0 on 2018-10-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='type_of_employee',
            new_name='head_bus_boy',
        ),
    ]
