# Generated by Django 2.0 on 2018-10-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181011_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='type',
        ),
    ]
