# Generated by Django 2.0 on 2018-10-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181015_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100)),
                ('type', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100)),
                ('type', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='available_shifts',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='scheduled_shifts',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.AddField(
            model_name='scheduledshifts',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Employee'),
        ),
        migrations.AddField(
            model_name='availableshifts',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Employee'),
        ),
    ]
