# Generated by Django 2.0 on 2018-10-15 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181015_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100)),
                ('type', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100)),
                ('type', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='availableshifts',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='scheduledshifts',
            name='employee',
        ),
        migrations.DeleteModel(
            name='AvailableShifts',
        ),
        migrations.DeleteModel(
            name='ScheduledShifts',
        ),
        migrations.AddField(
            model_name='employee',
            name='available_shifts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.AvailableShift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='scheduled_shifts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ScheduledShift'),
        ),
    ]
