# Generated by Django 2.0 on 2018-10-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181015_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='available_shifts',
        ),
        migrations.AddField(
            model_name='employee',
            name='available_shifts',
            field=models.ManyToManyField(blank=True, null=True, to='website.AvailableShift'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='scheduled_shifts',
        ),
        migrations.AddField(
            model_name='employee',
            name='scheduled_shifts',
            field=models.ManyToManyField(blank=True, null=True, to='website.ScheduledShift'),
        ),
    ]
