# Generated by Django 2.0 on 2018-10-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20181015_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='available_shifts',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='scheduled_shifts',
        ),
        migrations.AddField(
            model_name='availableshift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Employee'),
        ),
        migrations.AddField(
            model_name='scheduledshift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Employee'),
        ),
    ]
