# Generated by Django 2.0 on 2018-10-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_employee_number_of_scheduled_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='number_of_scheduled_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
