# Generated by Django 2.0 on 2018-10-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_postshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='number_of_scheduled_hours',
        ),
        migrations.AlterField(
            model_name='postshift',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100),
        ),
        migrations.AlterField(
            model_name='postshift',
            name='type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100),
        ),
    ]
