# Generated by Django 2.0 on 2018-11-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20181029_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableshift',
            name='employee',
        ),
        migrations.DeleteModel(
            name='AvailableShift',
        ),
    ]
