# Generated by Django 2.0 on 2018-11-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20181121_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postshift',
            name='day',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledshift',
            name='day',
            field=models.DateTimeField(),
        ),
    ]
